version: "3.7"

services:
  db:
    image: postgres:9.4-alpine
    volumes:
      - ./shared/postgresql:/var/lib/postgresql/data
    env_file:
      - .envs/.postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - helios-network

  app: &app
    container_name: helios-backend
    build:
      context: .
      dockerfile: docker/local/server/Dockerfile
    depends_on:
      - db
    env_file:
      - .envs/.django
      - .envs/.postgres
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    networks:
      - helios-network
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0.7
    networks:
      - helios-network

  celeryworker:
    <<: *app
    container_name: helios-celeryworker
    depends_on:
      - redis
      - db
    ports: []
    command: ["celery", "-A", "taskapp", "worker"]

networks:
  helios-network:
    name: helios-network
