# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("helios", "0005_remove_qrcode"),
        ("helios_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_title", models.TextField(default="", max_length=50)),
                ("session_id", models.TextField(default="")),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helios.Election",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helios_auth.User",
                    ),
                ),
            ],
        ),
    ]
