# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apolloassistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsession",
            name="secret_key",
            field=models.TextField(default=""),
        ),
    ]
