# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-22 20:38
from __future__ import unicode_literals

import apolloassistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolloassistant', '0002_assistantsession_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(unique=True)),
                ('value', models.TextField(default=apolloassistant.models._generate_cast_code, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LockInCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(unique=True)),
                ('value', models.TextField(default=apolloassistant.models._generate_lockin_code, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='assistantsession',
            name='election',
        ),
        migrations.RemoveField(
            model_name='assistantsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssistantSession',
        ),
    ]
