# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helios", "0002_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="session_title",
            field=models.TextField(default="", max_length=50),
        ),
    ]
