# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0004_auto_20200121_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='voter',
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
