# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0006_fakebooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakebooth',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helios.Election'),
        ),
    ]
