from ..helpers.env import env

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="django://")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERYD_TASK_TIME_LIMIT = 5 * 60
CELERYD_TASK_SOFT_TIME_LIMIT = 60
CELERY_TASKS_ALWAYS_EAGER = True
